# # Welcome to Jekyll!
# #
# # This config file is meant for settings that affect your whole blog, values
# # which you are expected to set up once and rarely need to edit after that.
# # For technical reasons, this file is *NOT* reloaded automatically when you use
# # 'jekyll serve'. If you change this file, please restart the server process.

# # Site settings
# title: 邓志成的博客
# email: superbulldeng@gmail.com
# description: > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://superbull.github.io" # the base hostname & protocol for your site
# twitter_username: superbull
# github_username:  superbull

# # Build settings
# markdown: kramdown


name: 邓志成的博客
description: Blogging about stuffs
meta_description: "Your New Jekyll Site, Blogging about stuffs"

markdown: kramdown
logo: false
paginate: 15
baseurl: /
domain_name: 'http://yourblog-domain.com'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'blog url'
author:         'Your Name'
